import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Juridisk information — Veyro Circle", description: "Privatliv, GDPR, handelsbetingelser, cookies, klager og sikkerhed for Veyro Circle." };

export default function LegalPage() {
  return <main className="legal-page">
    <header className="legal-header"><div><Link href="/" aria-label="Til Veyro Circle"><img src="/branding/veyro-systems-logo.png" alt="Veyro Systems" /></Link><Link href="/">← Tilbage til Veyro Circle</Link></div></header>
    <article className="legal-content">
      <header><p className="eyebrow">Veyro Circle</p><h1>Juridisk information</h1><p>Her finder du information om behandling af personoplysninger, abonnement, cookies, klagemuligheder og ansvar. Senest opdateret 7. oktober 2026.</p></header>
      <section className="legal-section" id="company"><h2>Virksomhedsoplysninger</h2><p>Veyro Circle udbydes af Veyro Systems ApS.</p><p className="legal-placeholder"><b>Skal udfyldes før lancering:</b> CVR-nummer, registreret virksomhedsadresse, juridisk kontakt-e-mail og eventuelt telefonnummer. Oplysningerne skal være korrekte og må ikke erstattes af testdata.</p></section>
      <section className="legal-section" id="privacy"><h2>Privatliv og GDPR</h2><p>Veyro Systems ApS er dataansvarlig for personoplysninger, der behandles i Veyro Circle. Vi behandler kun oplysninger, som er nødvendige for at levere og sikre tjenesten.</p><h3>Oplysninger og formål</h3><ul><li>Konto- og kontaktoplysninger bruges til login, profil, kommunikation og aftaler.</li><li>Annonce-, billed- og aftaleoplysninger bruges til at vise annoncer og gennemføre lån eller leje mellem brugere.</li><li>Betalings- og abonnementsstatus behandles via Stripe. Veyro Circle gemmer ikke fulde kortoplysninger.</li><li>Tekniske oplysninger kan behandles for drift, fejlfinding, sikkerhed og forebyggelse af misbrug.</li></ul><h3>Retsgrundlag, modtagere og opbevaring</h3><p>Behandlingen sker for at opfylde aftalen med brugeren, overholde retlige forpligtelser og varetage legitime interesser i sikker drift. Nødvendige databehandlere kan omfatte Firebase/Google Cloud, Netlify og Stripe. Oplysninger opbevares ikke længere end nødvendigt for formålet eller gældende dokumentationskrav.</p><h3>Favoritter, søgninger og fællesskab</h3><p>Favoritter og gemte søgninger knyttes til din konto. Efterlysninger viser dit fornavn og postområde, og er synlige i højst 30 dage. Undlad private kontaktoplysninger i offentlige tekster. Anmeldelser bygger på afsluttede aftaler; ejeranmeldelser kan vises ved annoncen, og begge parter kan se aftalens anmeldelser. Kalenderen viser optagede datoer uden at vise aftalens deltagere eller private noter. Godkendte forlængelser gemmes som tillæg til aftalen.</p><h3>Valgfrie push-notifikationer</h3><p>Hvis du aktiverer push på en enhed, bruger Circle Firebase Cloud Messaging til at sende besked om nye forespørgsler, chatbeskeder og nye annoncer, der matcher gemte søgninger med tilvalgte beskeder. Vi gemmer en teknisk enhedsregistrering knyttet til din konto, dit valgte sprog og registreringens udløbstid. Selve chatteksten, navn og adresse medsendes ikke. Registreringen udløber efter 30 dage uden fornyelse. Du kan slå push fra via klokken i Circle eller i enhedens indstillinger.</p><h3>Dine rettigheder</h3><p>Du kan efter omstændighederne få indsigt, berigtigelse, sletning, begrænsning, dataportabilitet og gøre indsigelse. Du kan klage til Datatilsynet på <a href="https://www.datatilsynet.dk/" target="_blank" rel="noreferrer">datatilsynet.dk</a>. Kontaktoplysninger til Veyro Systems ApS indsættes i virksomhedsafsnittet før lancering.</p></section>
      <section className="legal-section" id="terms"><h2>Handels- og abonnementsbetingelser</h2><p>Det er gratis at søge, låne og have én aktiv annonce. Circle Plus giver op til 20 aktive annoncer og sælges som et løbende månedsabonnement. Den aktuelle pris, valuta, faktureringsperiode og betalingsforpligtelse vises tydeligt umiddelbart før bestilling hos Stripe.</p><ul><li>Abonnementet fortsætter, indtil det opsiges via kontoens abonnementsstyring.</li><li>Opsigelse stopper fremtidig fornyelse; adgang fortsætter normalt til udgangen af den betalte periode.</li><li>Eventuel fortrydelsesret og tidspunktet for levering skal fremgå af det endelige checkout-flow.</li><li>Lån, leje, depositum og betaling mellem private brugere aftales direkte mellem parterne. Veyro Circle er ikke part i deres aftale og tager ikke provision.</li></ul><p className="legal-placeholder"><b>Før betaling åbnes:</b> De endelige vilkår skal juridisk kvalitetssikres, og checkout skal vise korrekt pris, fornyelse, opsigelse, leveringsstart og fortrydelsesoplysninger.</p></section>
      <section className="legal-section" id="cookies"><h2>Cookies og lokal lagring</h2><p>Veyro Circle må bruge teknisk nødvendig lagring til login, sikkerhed, sprogvalg og tjenestens grundfunktioner. Ikke-nødvendig statistik eller markedsføring må først aktiveres efter gyldigt samtykke. En samtykkeløsning skal tilføjes, hvis sådanne teknologier indføres.</p></section>
      <section className="legal-section" id="complaints"><h2>Klager</h2><p>Kontakt først Veyro Systems ApS på den juridiske kontaktadresse, som indsættes ovenfor. Hvis en forbrugertvist ikke løses, skal relevante oplysninger om godkendt klageorgan, adresse og hjemmeside fremgå her. Klager over behandling af personoplysninger kan indgives til Datatilsynet.</p><p className="legal-placeholder"><b>Skal udfyldes før lancering:</b> Relevant dansk og eventuelt svensk klageinstans afhængigt af salgsland og virksomhedens etableringssted.</p></section>
      <section className="legal-section" id="safety"><h2>Sikkerhed, identitet og ansvar</h2><p>Parterne bør kontrollere hinandens navn og adresse ved at se gyldig legitimation, gennemgå aftalen sammen og underskrive på telefonen eller på papir. Undgå at kopiere eller fotografere legitimation, medmindre der er et konkret og lovligt behov.</p><p>Beskriv tingens stand, pris, depositum, periode, aflevering og eventuelle skader i aftalen. Veyro Circle stiller platform og aftaleværktøj til rådighed, men kan ikke garantere en brugers identitet, en tings stand eller at en privat aftale bliver opfyldt.</p></section>
    </article>
  </main>;
}
