"use client";
import {useState} from "react";
import {communityFetch} from "@/lib/community-client";
import {agreementsChanged} from "@/lib/firebase-agreements";
import {type AgreementSchedule,validTime} from "@/lib/agreement-schedule";
import {dayCount,money,type Lang,type Country} from "@/lib/marketplace";
export function AgreementExtension({loan,uid,lang}:{loan:AgreementSchedule&{id:string;from:string;to:string;total:number;item:{dailyPrice:number;country:Country}};uid:string;lang:Lang}) {
  const [to,setTo]=useState(loan.to),[time,setTime]=useState(loan.returnTime??"17:00"),[busy,setBusy]=useState(false),[error,setError]=useState("");const da=lang==="da",p=loan.changeProposal;const days=dayCount(loan.from,to);
  async function act(action:string){setBusy(true);setError("");try{await communityFetch("/api/agreement-changes",{id:loan.id,action,to,returnTime:time,proposalId:p?.id});agreementsChanged();}catch(cause){setError(cause instanceof Error&&cause.message==="BOOKING_CONFLICT"?(da?"Forlængelsen overlapper en booking eller blokering. Vælg andre datoer.":"Förlängningen överlappar en bokning eller blockering. Välj andra datum."):(da?"Ændringen kunne ikke gemmes. Opdatér aftalen og prøv igen.":"Ändringen kunde inte sparas. Uppdatera avtalet och försök igen."));}finally{setBusy(false);}}
  return <section className="extra-panel no-print"><h3>{da?"Forlæng lånet":"Förläng lånet"}</h3>{p?<><p>{da?"Foreslået retur":"Föreslagen återlämning"}: {p.to} {p.returnTime} · {da?"Ny samlet lejepris":"Ny total hyra"}: <strong>{money(p.total,loan.item.country,lang)}</strong></p><p>{da?"Den oprindelige aftale gælder, indtil modparten godkender. Godkendelsen gemmes som et tillæg fra begge konti.":"Det ursprungliga avtalet gäller tills motparten godkänner. Godkännandet sparas som ett tillägg från båda kontona."}</p>{p.proposedBy!==uid&&<button disabled={busy} onClick={()=>void act("accept")}>{da?"Godkend ny slutdato og pris":"Godkänn nytt slutdatum och pris"}</button>}<button disabled={busy} onClick={()=>void act("decline")}>{p.proposedBy===uid?(da?"Træk forslag tilbage":"Dra tillbaka förslag"):(da?"Afvis forslag":"Avböj förslag")}</button></>:<><div className="date-search-row"><label>{da?"Ny slutdato":"Nytt slutdatum"}<input type="date" min={loan.to} value={to} onChange={e=>setTo(e.target.value)}/></label><label>{da?"Retur kl.":"Åter kl."}<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><p>{da?"Ny samlet lejepris":"Ny total hyra"}: {days?money(days*loan.item.dailyPrice,loan.item.country,lang):"—"}. {da?"Den aftalte dagspris og depositum bevares.":"Avtalat dagspris och deposition behålls."}</p><button disabled={busy||!days||to<=loan.to||!validTime(time)} onClick={()=>void act("propose")}>{da?"Foreslå forlængelse":"Föreslå förlängning"}</button></>}{error&&<p role="alert">{error}</p>}</section>;
}
