"use client";
import {Star} from "lucide-react";
import {useEffect,useState} from "react";
import {communityFetch} from "@/lib/community-client";
import type {Lang} from "@/lib/marketplace";
export function ReviewForm({id,lang,target="lender"}:{id:string;lang:Lang;target?:"lender"|"borrower"}) {
  const [reviews,setReviews]=useState<Array<Review&{own:boolean}>>([]);
  const [stars,setStars]=useState("0"),[text,setText]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");const da=lang==="da";
  useEffect(()=>{let active=true;communityFetch(`/api/reviews?agreementId=${encodeURIComponent(id)}`).then(d=>{if(active){setReviews(d.reviews);if(d.reviewed)setDone(true);}}).catch(()=>undefined);return()=>{active=false;};},[id]);
  return <section className="extra-panel no-print"><h3>{da?"Hvordan gik lånet?":"Hur gick lånet?"}</h3>{reviews.map((r,i)=><article key={i}><b>{r.author} · {r.stars}/{r.maxStars}</b><p>{r.text}</p></article>)}{done?<p role="status">{da?"Tak. Din anmeldelse er gemt.":"Tack. Ditt omdöme har sparats."}</p>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await communityFetch("/api/reviews",{id,stars:Number(stars),text});setDone(true);}catch(cause){setError(cause instanceof Error&&cause.message==="ALREADY_REVIEWED"?(da?"Du har allerede anmeldt denne aftale.":"Du har redan lämnat ett omdöme om avtalet."):(da?"Anmeldelsen kunne ikke gemmes. Begge skal have underskrevet returen.":"Omdömet kunde inte sparas. Båda måste ha signerat återlämningen."));}finally{setBusy(false);}}}><fieldset className="review-rating"><legend>{target==="lender"?(da?"Din vurdering af udlåneren":"Ditt omdöme om uthyraren"):(da?"Din vurdering af låneren":"Ditt omdöme om låntagaren")}</legend><div className="review-star-buttons" role="group" aria-label={da?"Vælg 1–6 stjerner":"Välj 1–6 stjärnor"}>{[1,2,3,4,5,6].map(n=><button key={n} type="button" aria-pressed={Number(stars)===n} aria-label={`${n} ${da?"af 6 stjerner":"av 6 stjärnor"}`} onClick={()=>setStars(String(n))}><Star aria-hidden="true" size={25} fill={n<=Number(stars)?"currentColor":"none"}/></button>)}</div><p>{Number(stars)>0?`${stars} / 6`:(da?"Vælg antal stjerner":"Välj antal stjärnor")}</p></fieldset><label>{da?"Kommentar (offentlig, højst 600 tegn)":"Kommentar (offentlig, högst 600 tecken)"}<textarea value={text} maxLength={600} onChange={e=>setText(e.target.value)} /></label><p>{da?"Beskriv oplevelsen sagligt. Undlad telefonnumre, adresser og andre private oplysninger.":"Beskriv upplevelsen sakligt. Undvik telefonnummer, adresser och andra privata uppgifter."}</p><button disabled={busy||Number(stars)<1}>{da?"Gem anmeldelse":"Spara omdöme"}</button>{error&&<p role="alert">{error}</p>}</form>}</section>;
}
type Review={author:string;stars:number;maxStars:number;text:string;createdAt:string};
export function ListingReviews({id,lang}:{id:string;lang:Lang}) {
  const [data,setData]=useState<{reviews:Review[];average:number|null;count:number}|null>(null),[failed,setFailed]=useState(false);
  useEffect(()=>{let active=true;fetch(`/api/reviews?listingId=${encodeURIComponent(id)}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(active)setData(d);}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[id]);
  return <section className="extra-panel lender-reviews"><h3>{lang==="da"?"Det siger lånerne om udlåneren":"Det säger låntagarna om uthyraren"}</h3><p>{lang==="da"?"Anmeldelser fra gennemførte lån":"Omdömen från avslutade lån"}</p>{failed?<p>{lang==="da"?"Anmeldelser kunne ikke hentes.":"Omdömen kunde inte hämtas."}</p>:!data?<p>…</p>:!data.count?<p>{lang==="da"?"Ingen anmeldelser endnu.":"Inga omdömen ännu."}</p>:<><p><strong>{data.average?.toLocaleString(lang==="da"?"da-DK":"sv-SE",{minimumFractionDigits:1,maximumFractionDigits:1})} / 6</strong> · {data.count}</p>{data.reviews.some(r=>r.maxStars===5)&&<p className="search-date-help">{lang==="da"?"Ældre anmeldelser vises på deres oprindelige 5-stjerneskala og omregnes forholdsmæssigt i gennemsnittet.":"Äldre omdömen visas på sin ursprungliga femstjärniga skala och räknas om proportionellt i genomsnittet."}</p>}{data.reviews.map((r,i)=><article key={i}><strong>{r.author}</strong><div className="review-stars" aria-label={`${r.stars} / ${r.maxStars}`}>{Array.from({length:r.maxStars},(_,n)=><Star aria-hidden="true" key={n} size={17} fill={n<r.stars?"currentColor":"none"}/>)}</div><span>{r.stars} / {r.maxStars}</span><small> · {r.createdAt.slice(0,10)}</small><p>{r.text}</p></article>)}</>}</section>;
}
