"use client";
import {useState} from "react";
import {communityFetch} from "@/lib/community-client";
import {matchesSearch,type Preferences,type SearchFilter} from "@/lib/discovery";
import type {Lang,Place} from "@/lib/marketplace";
export function SavedSearches({lang,prefs,filter,onChange,onApply,items}:{lang:Lang;prefs:Preferences;filter:SearchFilter;onChange:(prefs:Preferences)=>void;onApply:(filter:SearchFilter)=>void;items:Array<{owned?:boolean;id:string;createdAt?:string;name:string;description:string;country:string;category:string;dailyPrice:number;place:Place;city:string}>}) {
  const [alerts,setAlerts]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");const da=lang==="da";
  async function act(body:unknown) {setBusy(true);setError("");try{onChange(await communityFetch("/api/preferences",body));}catch{setError(da?"Kunne ikke gemme. Vælg et sted ved afstandssøgning, eller prøv igen (højst 20 søgninger).":"Kunde inte spara. Välj en ort vid avståndssökning eller försök igen (högst 20 sökningar).");}finally{setBusy(false);}}
  return <details className="extra-panel saved-searches"><summary>{da?"Gemte søgninger":"Sparade sökningar"} ({prefs.searches.length})</summary><p>{da?"Gem ting, kategori, sted og prisfilter. Datoer gemmes ikke, så søgningen også kan bruges senere.":"Spara sak, kategori, ort och prisfilter. Datum sparas inte så att sökningen kan användas senare."}</p><label className="check-label"><input type="checkbox" checked={alerts} onChange={e=>setAlerts(e.target.checked)} />{da?"Giv besked om nye annoncer, der matcher (push kræver aktivering på enheden)":"Meddela om nya matchande annonser (push kräver aktivering på enheten)"}</label><button disabled={busy} onClick={()=>void act({action:"saveSearch",filter,alerts})}>{da?"Gem denne søgning":"Spara den här sökningen"}</button>{prefs.searches.map(s=>{const count=s.alerts?items.filter(i=>!i.owned&&i.createdAt&&i.createdAt>s.seenThrough&&matchesSearch(s,i)).length:0;return <div className="saved-search-row" key={s.id}><button disabled={busy} onClick={()=>{onApply(s);void act({action:"seenSearch",id:s.id});}}>{s.query|| (da?"Alle ting":"Alla saker")} · {s.country} · {s.radius==="all"?"∞":s.radius+" km"}{count>0&&<strong> · {count} {da?"nye":"nya"}</strong>}</button><button disabled={busy} onClick={()=>void act({action:"removeSearch",id:s.id})}>{da?"Fjern":"Ta bort"}</button></div>;})}{error&&<p role="alert">{error}</p>}</details>;
}
