"use client";
import {useState} from "react";
import {communityFetch} from "@/lib/community-client";
import {matchesSearch,type Preferences,type SearchFilter} from "@/lib/discovery";
import type {Lang,Place} from "@/lib/marketplace";
export function SavedSearches({lang,prefs,filter,onChange,onApply,items,mode="list",onLogin}:{mode?:"save"|"list";onLogin?:()=>void;lang:Lang;prefs:Preferences;filter:SearchFilter;onChange:(prefs:Preferences)=>void;onApply:(filter:SearchFilter)=>void;items:Array<{owned?:boolean;id:string;createdAt?:string;name:string;description:string;country:string;category:string;dailyPrice:number;place:Place;city:string}>}) {
  const [alerts,setAlerts]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);const da=lang==="da";
  async function act(body:unknown) {setBusy(true);setError("");setSaved(false);try{onChange(await communityFetch("/api/preferences",body));setSaved(true);}catch{setError(da?"Kunne ikke gemme. Vælg et sted ved afstandssøgning, eller prøv igen (højst 20 søgninger).":"Kunde inte spara. Välj en ort vid avståndssökning eller försök igen (högst 20 sökningar).");}finally{setBusy(false);}}
  if(mode === "save") return <div className="save-search-controls"><button disabled={busy} onClick={()=>{if(onLogin){onLogin();return;}void act({action:"saveSearch",filter,alerts});}}>{busy?(da?"Gemmer…":"Sparar…"):(da?"Gem søgning":"Spara sökning")}</button><label className="check-label"><input type="checkbox" checked={alerts} onChange={e=>setAlerts(e.target.checked)} />{da?"Giv besked om nye match":"Meddela om nya träffar"}</label><small>{da?"Gemmer filtre, men ikke datoer. Push kræver aktivering på enheden.":"Sparar filter, men inte datum. Push kräver aktivering på enheten."}</small>{saved&&<p role="status">{da?"Søgningen er gemt under Gemte søgninger.":"Sökningen finns under Sparade sökningar."}</p>}{error&&<p role="alert">{error}</p>}</div>;
  return <div className="saved-searches">{!prefs.searches.length&&<p>{da?"Du har ingen gemte søgninger endnu. Brug Gem søgning på forsiden.":"Du har inga sparade sökningar ännu. Använd Spara sökning på startsidan."}</p>}{prefs.searches.map(s=>{const count=s.alerts?items.filter(i=>!i.owned&&i.createdAt&&i.createdAt>s.seenThrough&&matchesSearch(s,i)).length:0;return <div className="saved-search-row" key={s.id}><button disabled={busy} onClick={()=>{onApply(s);void act({action:"seenSearch",id:s.id});}}>{s.query|| (da?"Alle ting":"Alla saker")} · {s.country} · {s.radius==="all"?"∞":s.radius+" km"}{count>0&&<strong> · {count} {da?"nye":"nya"}</strong>}</button><button disabled={busy} onClick={()=>void act({action:"removeSearch",id:s.id})}>{da?"Fjern":"Ta bort"}</button></div>;})}{error&&<p role="alert">{error}</p>}</div>;
}
