"use client";
import {useEffect,useState} from "react";
import {communityFetch} from "@/lib/community-client";
import {circleToday} from "@/lib/agreement-workflow";
import {distanceKm,type Place,type Lang} from "@/lib/marketplace";
type Wanted={id:string;title:string;description:string;author:string;place:Place;from:string;to:string;owned:boolean;offers:Array<{listingId:string}>};
export function WantedBoard({lang,uid,origin,radius,items,onOpen,onLogin}:{lang:Lang;uid?:string;origin:Place|null;radius:string;items:Array<{id:string;name:string;owned?:boolean}>;onOpen:(id:string)=>void;onLogin:()=>void}) {
  const [rows,setRows]=useState<Wanted[]>([]),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[from,setFrom]=useState(circleToday()),[to,setTo]=useState(circleToday()),[offers,setOffers]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[version,setVersion]=useState(0);const da=lang==="da";
  useEffect(()=>{let active=true;const load=uid?communityFetch("/api/wanted"):fetch("/api/wanted",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();return r.json();});load.then(d=>{if(active)setRows(d.items);}).catch(()=>{if(active)setError(da?"Efterlysninger kunne ikke hentes.":"Efterlysningar kunde inte hämtas.");});return()=>{active=false;};},[uid,version,da]);
  async function act(body:Record<string,unknown>){if(!uid){onLogin();return;}setBusy(true);setError("");setSuccess("");try{await communityFetch("/api/wanted",body);setVersion(v=>v+1);if(body.action==="create"){setTitle("");setDescription("");}setSuccess(da?"Gemt. Se dine efterlysninger og svar her på siden.":"Sparat. Se dina efterlysningar och svar här på sidan.");}catch{setError(da?"Kunne ikke gemme. Kontrollér datoer og profil. Højst 5 aktive efterlysninger og 20 svar pr. efterlysning.":"Kunde inte spara. Kontrollera datum och profil. Högst 5 aktiva efterlysningar och 20 svar per efterlysning.");}finally{setBusy(false);}}
  const local=rows.filter(r=>r.owned||radius==="all"||!!origin&&distanceKm(origin,r.place)<=Number(radius));
  return <section className="wanted-board"><p>{da?"Mangler du noget i nærheden? Efterlys det her. Opslaget vises i højst 30 dage, og kun postområde vises. Svar er forslag til annoncer; en låneaftale oprettes først via en almindelig forespørgsel.":"Saknar du något i närheten? Efterlys det här. Inlägget visas i högst 30 dagar och bara postområdet visas. Svar är förslag på annonser; ett låneavtal skapas först via en vanlig förfrågan."}</p><details className="extra-panel"><summary>{da?"Opret en efterlysning":"Skapa en efterlysning"}</summary>{!uid?<button onClick={onLogin}>{da?"Log ind for at efterlyse":"Logga in för att efterlysa"}</button>:<form onSubmit={e=>{e.preventDefault();void act({action:"create",title,description,from,to});}}><label>{da?"Jeg søger":"Jag söker"}<input required minLength={3} maxLength={100} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>{da?"Beskrivelse — ingen private kontaktoplysninger":"Beskrivning — inga privata kontaktuppgifter"}<textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="date-search-row"><label>{da?"Fra":"Från"}<input type="date" required min={circleToday()} value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{da?"Til":"Till"}<input type="date" required min={from} value={to} onChange={e=>setTo(e.target.value)}/></label></div><button disabled={busy}>{da?"Opret efterlysning":"Skapa efterlysning"}</button></form>}</details>{error&&<p role="alert">{error}</p>}{success&&<p role="status">{success}</p>}<p>{da?"Seneste efterlysninger i dit søgeområde (op til 100)":"Senaste efterlysningarna i ditt sökområde (upp till 100)"}</p>{local.length===0&&<p>{da?"Ingen efterlysninger her endnu.":"Inga efterlysningar här ännu."}</p>}{local.map(r=><article className="extra-panel" key={r.id}><h3>{r.title}</h3><p>{r.description}</p><p>{r.author} · {r.place.postcode} {r.place.city} · {r.from} – {r.to}</p>{r.owned?<><button disabled={busy} onClick={()=>void act({action:"close",id:r.id})}>{da?"Luk efterlysning":"Stäng efterlysning"}</button><p>{da?"Tilbudte ting":"Föreslagna saker"}: {r.offers.length}</p>{r.offers.map(o=><button key={o.listingId} onClick={()=>onOpen(o.listingId)}>{items.find(i=>i.id===o.listingId)?.name??(da?"Annonce ikke længere tilgængelig":"Annonsen är inte längre tillgänglig")}</button>)}</>:<div><label>{da?"Tilbyd en af dine ting":"Erbjud en av dina saker"}<select value={offers[r.id]??""} onChange={e=>setOffers(v=>({...v,[r.id]:e.target.value}))}><option value="">{da?"Vælg annonce":"Välj annons"}</option>{items.filter(i=>i.owned).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><button disabled={busy||!!uid&&!offers[r.id]} onClick={()=>void act({action:"offer",id:r.id,listingId:offers[r.id]})}>{uid?(da?"Send forslag":"Skicka förslag"):(da?"Log ind":"Logga in")}</button></div>}</article>)}</section>;
}
