import { agreementStage, type WorkflowAgreement } from "./agreement-workflow";

export function agreementGuidance(a: WorkflowAgreement, uid: string, lang: "da" | "sv", names: {borrower:string;lender:string}) {
  const da = lang === "da";
  const stage = agreementStage(a);
  const connected = Boolean(a.borrowerUid && a.lenderUid && a.borrowerUid !== a.lenderUid);
  const participant = uid === a.borrowerUid || uid === a.lenderUid;
  const mine = uid === a.borrowerUid ? a.borrowerSignature : a.lenderSignature;
  const myReturn = uid === a.borrowerUid ? a.borrowerReturnSignature : a.lenderReturnSignature;
  const other = uid === a.borrowerUid ? names.lender : names.borrower;
  const current = stage === "requested" ? 0 : stage === "accepted" ? 1 : stage === "handedOver" ? (a.borrowerReturnSignature || a.lenderReturnSignature ? 3 : 2) : stage === "returned" ? 3 : -1;
  const base = {connected, current, complete:stage === "returned", stopped:stage === "declined" || stage === "cancelled", labels:da ? ["Forespørgsel", "Udlevering", "I brug", "Tilbagelevering"] : ["Förfrågan", "Utlämning", "Används", "Återlämning"]};
  if (base.stopped) return {...base, title:stage === "declined" ? (da ? "Forespørgslen er afvist" : "Förfrågan har avböjts") : (da ? "Aftalen er annulleret" : "Avtalet har avbrutits"), detail:da ? "Der er ingen næste handling. Aftalen ligger i arkivet." : "Ingen ytterligare åtgärd behövs. Avtalet finns i arkivet.", target:null};
  if (base.complete) return {...base, title:da ? "Tilbageleveringen er afsluttet" : "Återlämningen är avslutad", detail:da ? "Begge parter har underskrevet returkvitteringen. Du kan se aftalen i arkivet og udskrive den." : "Båda parter har signerat returkvittot. Du kan se avtalet i arkivet och skriva ut det.", target:null};
  if (!connected) return {...base,current:-1,title:da ? "Aftalen kan ikke afsluttes digitalt" : "Avtalet kan inte slutföras digitalt",detail:da ? "Aftalen er ikke knyttet til to forskellige brugerkonti. Det kan være en gammel prøveaftale. Opret en ny forespørgsel på en rigtig annonce; eksisterende noter og underskrifter bevares." : "Avtalet är inte kopplat till två olika användarkonton. Det kan vara ett äldre testavtal. Skapa en ny förfrågan på en riktig annons; befintliga anteckningar och signaturer bevaras.",target:null};
  if (!participant) return {...base,title:da ? "Kun aftalens parter kan underskrive" : "Endast avtalsparterna kan signera",detail:da ? "Åbn aftalen fra den konto, der er angivet som låner eller ejer." : "Öppna avtalet från kontot som anges som låntagare eller ägare.",target:null};
  if (stage === "requested") return {...base,title:uid === a.lenderUid ? (da ? "Du skal svare på forespørgslen" : "Du behöver svara på förfrågan") : (da ? `Afventer svar fra ${names.lender}` : `Inväntar svar från ${names.lender}`),detail:da ? "Ejeren godkender eller afviser under Mine lån → Jeg udlåner. Først efter godkendelsen kan I skrive udleveringsnote og underskrive." : "Ägaren godkänner eller avböjer under Mina lån → Jag lånar ut. Efter godkännandet kan ni skriva utlämningsanteckningen och signera.",target:null};
  if (stage === "accepted") return {...base,title:mine ? (da ? `Afventer ${other}s underskrift ved udlevering` : `Inväntar ${other}s signatur vid utlämning`) : (da ? "Din underskrift ved udlevering mangler" : "Din signatur vid utlämning saknas"),detail:a.borrowerSignature || a.lenderSignature ? (da ? "Udleveringsnoten er låst af den første underskrift. Den anden part skal læse den samme note og underskrive fra sin egen konto. Derefter åbnes returnoten." : "Utlämningsanteckningen är låst av den första signaturen. Den andra parten läser samma anteckning och signerar från sitt eget konto. Därefter öppnas returanteckningen.") : (da ? "Skriv og gem eventuelle skader i udleveringsnoten, før nogen underskriver. Begge parter læser noten og underskriver fra hver sin konto ved udleveringen." : "Skriv och spara eventuella skador i utlämningsanteckningen innan någon signerar. Båda parter läser anteckningen och signerar från varsitt konto vid utlämningen."),target:mine ? null : "handover"};
  return {...base,title:myReturn ? (da ? `Afventer ${other}s returunderskrift` : `Inväntar ${other}s retursignatur`) : (da ? "Ved tilbagelevering: kontrollér stand og underskriv" : "Vid återlämning: kontrollera skicket och signera"),detail:a.borrowerReturnSignature || a.lenderReturnSignature ? (da ? "Returnoten er låst. Aftalen afsluttes først, når den anden part har læst noten og underskrevet fra sin egen konto." : "Returanteckningen är låst. Avtalet avslutas först när den andra parten har läst anteckningen och signerat från sitt eget konto.") : (da ? "Tingen er udleveret. Når den returneres, skriver og gemmer I eventuelle skader i returnoten, før nogen underskriver. Underskriv først, når tingen faktisk er afleveret." : "Saken har lämnats ut. När den återlämnas skriver och sparar ni eventuella skador i returanteckningen innan någon signerar. Signera först när saken faktiskt har återlämnats."),target:myReturn ? null : "return"};
}
